#include <linux/types.h>
#include <linux/userfaultfd.h>

#ifdef UFFD_API
const __u64 _const_UFFD_API = UFFD_API;
#endif

#ifdef UFFD_API_FEATURES
const __u64 _const_UFFD_API_FEATURES = UFFD_API_FEATURES;
#endif

#ifdef UFFD_API_IOCTLS
const __u64 _const_UFFD_API_IOCTLS = UFFD_API_IOCTLS;
#endif

#ifdef UFFD_API_RANGE_IOCTLS
const __u64 _const_UFFD_API_RANGE_IOCTLS = UFFD_API_RANGE_IOCTLS;
#endif

#ifdef UFFD_API_RANGE_IOCTLS_BASIC
const __u64 _const_UFFD_API_RANGE_IOCTLS_BASIC = UFFD_API_RANGE_IOCTLS_BASIC;
#endif

#ifdef UFFDIO_REGISTER_MODE_MISSING
const __u64 _const_UFFDIO_REGISTER_MODE_MISSING = UFFDIO_REGISTER_MODE_MISSING;
#endif

#ifdef UFFDIO_REGISTER_MODE_WP
const __u64 _const_UFFDIO_REGISTER_MODE_WP = UFFDIO_REGISTER_MODE_WP;
#endif

#ifdef UFFDIO_COPY_MODE_DONTWAKE
const __u64 _const_UFFDIO_COPY_MODE_DONTWAKE = UFFDIO_COPY_MODE_DONTWAKE;
#endif

#ifdef UFFDIO_ZEROPAGE_MODE_DONTWAKE
const __u64 _const_UFFDIO_ZEROPAGE_MODE_DONTWAKE = UFFDIO_ZEROPAGE_MODE_DONTWAKE;
#endif

