name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest, ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v2

    # Keep this step, so that we can check that the Linux kernel is the one we
    # expect, depending on the runner kernel.
    - name: Check Linux version
      run: uname -r

    # /dev/userfaultfd is only present on ubuntu-latest.
    - name: Setup access to /dev/userfaultfd
      run: sudo setfacl -m u:${USER}:rw /dev/userfaultfd

    - name: Build
      run: cargo build --verbose

    - name: Run tests (Linux 4.11 support)
      run: cargo test --verbose
    - name: Run tests (Linux 4.14 support)
      run: cargo test --verbose --features linux4_14

    - name: Run tests (Linux 5.7 support)
      run: cargo test --verbose --features linux5_7

  audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo Audit
      run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
